POST /runs/batch HTTP/1.1
Host: localhost:3000
User-Agent: langsmith-py/0.1.120
Accept: application/json
Connection: keep-alive
x-api-key: ls__1560a0b445f74038848a5d32fc89f4eb
Content-Type: application/json
Content-Length: 3775

{
    "post": [
        {
            "id": "46a9ea42-2f8f-4338-a1ff-56ea7cb214af",
            "start_time": "2024-10-29T02:16:17.417591+00:00",
            "end_time": null,
            "extra": {
                "invocation_params": {
                    "model": "gpt-4o",
                    "model_name": "gpt-4o",
                    "stream": false,
                    "n": 1,
                    "temperature": 0.0,
                    "max_tokens": 4096,
                    "_type": "openai-chat",
                    "stop": null
                },
                "options": {
                    "stop": null
                },
                "batch_size": 1,
                "metadata": {
                    "ls_provider": "openai",
                    "ls_model_name": "gpt-4o",
                    "ls_model_type": "chat",
                    "ls_temperature": 0.0,
                    "ls_max_tokens": 4096,
                    "revision_id": "refs/tags/v0.2.6-535-g496123b-dirty"
                },
                "runtime": {
                    "sdk": "langsmith-py",
                    "sdk_version": "0.1.120",
                    "library": "langchain-core",
                    "platform": "macOS-15.0.1-arm64-arm-64bit",
                    "runtime": "python",
                    "py_implementation": "CPython",
                    "runtime_version": "3.11.7",
                    "langchain_version": "0.2.16",
                    "langchain_core_version": "0.2.39",
                    "library_version": "0.2.39"
                }
            },
            "error": null,
            "serialized": {
                "lc": 1,
                "type": "constructor",
                "id": [
                    "langchain",
                    "chat_models",
                    "openai",
                    "ChatOpenAI"
                ],
                "kwargs": {
                    "model_name": "gpt-4o",
                    "temperature": 0.0,
                    "openai_api_key": {
                        "lc": 1,
                        "type": "secret",
                        "id": [
                            "OPENAI_API_KEY"
                        ]
                    },
                    "openai_api_base": "https://ai.liaobots.work/v1",
                    "openai_proxy": "",
                    "max_retries": 2,
                    "n": 1,
                    "max_tokens": 4096
                },
                "name": "ChatOpenAI"
            },
            "events": [
                {
                    "name": "start",
                    "time": "2024-10-29T02:16:17.417591+00:00"
                }
            ],
            "reference_example_id": null,
            "parent_run_id": null,
            "tags": [],
            "trace_id": "46a9ea42-2f8f-4338-a1ff-56ea7cb214af",
            "dotted_order": "20241029T021617417591Z46a9ea42-2f8f-4338-a1ff-56ea7cb214af",
            "outputs": null,
            "session_name": "zs-dev",
            "name": "ChatOpenAI",
            "inputs": {
                "messages": [
                    [
                        {
                            "lc": 1,
                            "type": "constructor",
                            "id": [
                                "langchain",
                                "schema",
                                "messages",
                                "HumanMessage"
                            ],
                            "kwargs": {
                                "content": "hi",
                                "type": "human"
                            }
                        }
                    ]
                ]
            },
            "run_type": "llm"
        }
    ]
}